'use strict';

 let data = [
     {
         "_id": "57addab2b8accfb12c47bab0",
         "index": 0,
         "guid": "69e2f39e-5d11-4c61-8e79-05780dc3a483",
         "isActive": false,
         "balance": "$1,426.92",
         "picture": "http://placehold.it/32x32",
         "age": 30,
         "eyeColor": "green",
         "name": "Anastasia Blackburn",
         "gender": "female",
         "company": "QUANTASIS",
         "email": "anastasiablackburn@quantasis.com",
         "phone": "+1 (814) 516-2336",
         "address": "298 Royce Place, Ezel, Montana, 2989",
         "about": "Pariatur est do amet labore adipisicing fugiat occaecat amet aute do do aliqua cillum. Enim nulla nulla consequat esse deserunt. Irure incididunt duis Lorem culpa quis proident. Ut consectetur mollit duis nulla ut nisi nostrud minim ad elit nulla irure enim laboris. Sint qui esse deserunt ad in sunt dolor enim enim occaecat id enim qui ut. Eu culpa deserunt Lorem sit esse.\r\n"
     },
     {
         "_id": "57addab2c0cb7399ade459ce",
         "index": 1,
         "guid": "7471d7bb-ceaf-4f8d-b4ea-5d0a1229c223",
         "isActive": true,
         "balance": "$2,296.24",
         "picture": "http://placehold.it/32x32",
         "age": 20,
         "eyeColor": "brown",
         "name": "Frazier Fleming",
         "gender": "male",
         "company": "DARWINIUM",
         "email": "frazierfleming@darwinium.com",
         "phone": "+1 (964) 434-2499",
         "address": "611 Kings Place, Machias, Washington, 9977",
         "about": "Ipsum enim qui amet nostrud et anim officia nostrud qui mollit labore est dolor eu. Fugiat culpa eiusmod id amet eu occaecat anim et culpa consequat et. Cillum incididunt sint officia incididunt laborum. Officia mollit laboris aliqua qui laboris excepteur. Ad ex eiusmod eu proident officia consequat deserunt laborum. Officia excepteur nisi aliqua ad ad labore. Et minim eu commodo exercitation do non eiusmod.\r\n"
     },
     {
         "_id": "57addab229d8a1009458fcc3",
         "index": 2,
         "guid": "e5ef89b0-6b2c-4a90-9c03-ebea6b238d64",
         "isActive": true,
         "balance": "$1,423.81",
         "picture": "http://placehold.it/32x32",
         "age": 22,
         "eyeColor": "green",
         "name": "Sweet Myers",
         "gender": "male",
         "company": "SLOFAST",
         "email": "sweetmyers@slofast.com",
         "phone": "+1 (991) 406-3478",
         "address": "687 Degraw Street, Devon, New Mexico, 3015",
         "about": "Duis voluptate laborum in incididunt eu Lorem nulla occaecat ut non. Non magna minim incididunt irure ad ut. Et consectetur aliquip consectetur incididunt nisi. Nisi culpa irure culpa esse veniam ad irure Lorem pariatur consequat mollit dolor est laboris. Eu laboris sint ea qui deserunt nostrud sit nostrud. Sit tempor non eiusmod deserunt.\r\n"
     },
     {
         "_id": "57addab27363cf77647b2dd5",
         "index": 3,
         "guid": "6952b425-ff87-462d-a1f0-ac0818d0a787",
         "isActive": false,
         "balance": "$2,574.96",
         "picture": "http://placehold.it/32x32",
         "age": 24,
         "eyeColor": "brown",
         "name": "Mary Hughes",
         "gender": "female",
         "company": "URBANSHEE",
         "email": "maryhughes@urbanshee.com",
         "phone": "+1 (826) 576-2891",
         "address": "917 Stuart Street, Whitmer, Texas, 6713",
         "about": "Deserunt laboris tempor qui ipsum id laborum nisi. Cillum eiusmod laboris mollit est Lorem minim Lorem nisi culpa. Anim elit aliquip consequat velit incididunt. Esse Lorem aliquip irure culpa laboris officia fugiat laboris voluptate veniam dolor nisi ad id. Est consectetur et cillum esse fugiat voluptate ullamco commodo dolor nostrud officia laborum. Aliqua veniam in ullamco elit exercitation fugiat reprehenderit enim esse cupidatat sint id eiusmod deserunt. Minim sit aliquip consectetur enim nulla laborum non sit tempor cupidatat ad incididunt ipsum.\r\n"
     },
     {
         "_id": "57addab2c6d2f24c061fb40b",
         "index": 4,
         "guid": "1717a75f-7eb0-49f9-93b3-70f1d060ac76",
         "isActive": false,
         "balance": "$2,353.70",
         "picture": "http://placehold.it/32x32",
         "age": 38,
         "eyeColor": "blue",
         "name": "Candice Berg",
         "gender": "female",
         "company": "AUTOGRATE",
         "email": "candiceberg@autograte.com",
         "phone": "+1 (972) 550-2544",
         "address": "316 Brooklyn Avenue, Emerald, South Carolina, 5171",
         "about": "Cillum quis non fugiat dolore aliquip consequat ex et. Cillum commodo laboris nostrud ullamco irure labore fugiat aliqua cillum veniam velit nostrud commodo excepteur. Officia laboris magna consequat esse dolor deserunt labore incididunt consectetur cillum ipsum ad enim et. Id dolore pariatur excepteur est sunt. Culpa exercitation laborum ut dolor eu laboris labore.\r\n"
     },
     {
         "_id": "57addab2f5d26ae2f4b33f7b",
         "index": 5,
         "guid": "be89bff1-4fcd-4518-b716-5734c206fc84",
         "isActive": true,
         "balance": "$1,146.56",
         "picture": "http://placehold.it/32x32",
         "age": 36,
         "eyeColor": "green",
         "name": "Bonita Buchanan",
         "gender": "female",
         "company": "SUREMAX",
         "email": "bonitabuchanan@suremax.com",
         "phone": "+1 (935) 593-2747",
         "address": "376 Kossuth Place, Tyro, Alabama, 8602",
         "about": "Qui esse id et consectetur proident. Irure est nulla consectetur consequat consequat irure irure et velit. Consequat voluptate dolor nulla eu. Dolore culpa incididunt ullamco voluptate esse cillum esse est id dolor consequat duis Lorem incididunt. Ullamco mollit non proident mollit ipsum dolore ullamco fugiat commodo labore quis qui officia. Reprehenderit dolore duis cillum velit cupidatat veniam fugiat incididunt veniam.\r\n"
     },
     {
         "_id": "57addab25e1f24e7ad4d7996",
         "index": 6,
         "guid": "05311e47-533d-4c32-926b-85ddb1572d4a",
         "isActive": false,
         "balance": "$2,603.16",
         "picture": "http://placehold.it/32x32",
         "age": 23,
         "eyeColor": "blue",
         "name": "Rene Torres",
         "gender": "female",
         "company": "ENOMEN",
         "email": "renetorres@enomen.com",
         "phone": "+1 (988) 549-3375",
         "address": "949 Gotham Avenue, Davenport, Oklahoma, 1809",
         "about": "Minim pariatur ad Lorem ipsum ad. Exercitation laborum Lorem velit dolore in ut. Do et excepteur qui enim fugiat nostrud in dolore laborum eiusmod exercitation. Enim ut esse reprehenderit officia nostrud do aute amet deserunt non aute velit elit ut.\r\n"
     },
     {
         "_id": "57addab2f4c41405b3f20f6d",
         "index": 7,
         "guid": "5e4a581f-a1af-4513-b254-cc73fd933e04",
         "isActive": false,
         "balance": "$2,142.28",
         "picture": "http://placehold.it/32x32",
         "age": 20,
         "eyeColor": "brown",
         "name": "Sweeney Alexander",
         "gender": "male",
         "company": "ASSURITY",
         "email": "sweeneyalexander@assurity.com",
         "phone": "+1 (991) 413-2528",
         "address": "817 Amherst Street, Libertytown, Wisconsin, 2282",
         "about": "Officia sit velit proident eiusmod qui. Incididunt nisi Lorem amet laboris irure ut adipisicing non et est velit. Elit reprehenderit aliquip mollit consectetur elit laboris non in cillum aute pariatur.\r\n"
     },
     {
         "_id": "57addab20c9901995a10e3f7",
         "index": 8,
         "guid": "808417a2-e4b8-4304-8603-1ee1e549aac4",
         "isActive": false,
         "balance": "$3,273.99",
         "picture": "http://placehold.it/32x32",
         "age": 40,
         "eyeColor": "green",
         "name": "Beard Peck",
         "gender": "male",
         "company": "GEEKMOSIS",
         "email": "beardpeck@geekmosis.com",
         "phone": "+1 (941) 561-3569",
         "address": "846 Beekman Place, Kaka, North Carolina, 701",
         "about": "Esse qui elit aliquip voluptate veniam anim ipsum ut ut ullamco ipsum eu cillum. Qui amet nulla deserunt ea commodo. Culpa officia mollit voluptate magna veniam non irure qui consequat qui mollit occaecat incididunt eiusmod. Do dolor quis voluptate do incididunt dolore ad et ipsum do ipsum proident minim. Exercitation do excepteur incididunt officia sint in exercitation esse. Cillum in deserunt adipisicing ipsum consequat culpa cupidatat exercitation adipisicing id culpa nisi cupidatat. Lorem dolor minim excepteur tempor dolore aute do adipisicing exercitation et esse est aute.\r\n"
     },
     {
         "_id": "57addab2f2e546e38152eaf0",
         "index": 9,
         "guid": "e46d704e-5e23-4e69-9c95-b639aeb77dd6",
         "isActive": true,
         "balance": "$3,975.84",
         "picture": "http://placehold.it/32x32",
         "age": 35,
         "eyeColor": "green",
         "name": "Potts Glenn",
         "gender": "male",
         "company": "CAPSCREEN",
         "email": "pottsglenn@capscreen.com",
         "phone": "+1 (966) 492-2533",
         "address": "994 Dean Street, Orovada, Kentucky, 956",
         "about": "Mollit magna exercitation proident do deserunt. Tempor do elit sit ut. Laborum duis proident reprehenderit aliquip est fugiat id proident consectetur occaecat eu. Sunt ut officia dolore pariatur officia ut commodo voluptate fugiat ipsum sunt adipisicing proident.\r\n"
     },
     {
         "_id": "57addab2ef87218f4390424f",
         "index": 10,
         "guid": "0b4f7029-4f06-4b72-9ba9-0af7d9d6b81c",
         "isActive": false,
         "balance": "$2,812.82",
         "picture": "http://placehold.it/32x32",
         "age": 36,
         "eyeColor": "blue",
         "name": "Aimee Hewitt",
         "gender": "female",
         "company": "HIVEDOM",
         "email": "aimeehewitt@hivedom.com",
         "phone": "+1 (858) 448-2596",
         "address": "931 Division Place, Itmann, Maine, 6205",
         "about": "Id aliqua commodo et incididunt nostrud minim pariatur dolore cillum proident amet sunt sunt labore. Veniam tempor in dolor Lorem magna non ullamco ut do veniam deserunt eu duis. Enim reprehenderit officia dolor est amet eu ullamco nostrud. Quis occaecat in exercitation minim ut et tempor.\r\n"
     },
     {
         "_id": "57addab2366c71dd3b46baeb",
         "index": 11,
         "guid": "b6d9d3dd-17b0-4525-9219-32a7c8722a40",
         "isActive": false,
         "balance": "$3,189.34",
         "picture": "http://placehold.it/32x32",
         "age": 30,
         "eyeColor": "brown",
         "name": "Becker Barnett",
         "gender": "male",
         "company": "BUZZWORKS",
         "email": "beckerbarnett@buzzworks.com",
         "phone": "+1 (970) 550-2432",
         "address": "734 Seigel Street, Kipp, Alaska, 5298",
         "about": "In laborum esse amet fugiat ipsum voluptate excepteur culpa. Exercitation ut mollit sunt cillum ex cupidatat culpa et aliquip sit nulla laborum id ipsum. Aute ut id deserunt irure labore non consequat. Fugiat eu in pariatur ea do velit esse esse nostrud adipisicing incididunt voluptate amet dolore.\r\n"
     },
     {
         "_id": "57addab26a07f035dd336367",
         "index": 12,
         "guid": "bc6544e9-3ac2-427c-be17-2e5da65967c8",
         "isActive": false,
         "balance": "$1,473.38",
         "picture": "http://placehold.it/32x32",
         "age": 35,
         "eyeColor": "brown",
         "name": "Maryann Thomas",
         "gender": "female",
         "company": "FILODYNE",
         "email": "maryannthomas@filodyne.com",
         "phone": "+1 (837) 410-2153",
         "address": "872 Bouck Court, Alleghenyville, Oregon, 2971",
         "about": "Incididunt consectetur nisi Lorem mollit laboris officia laboris labore. Dolor mollit eiusmod duis cillum non culpa minim pariatur fugiat ex. Consequat aute in occaecat exercitation nostrud fugiat laboris ullamco. Et cillum pariatur nostrud mollit commodo sint et et reprehenderit dolore aute. Duis do laboris ex nulla nostrud et esse.\r\n"
     },
     {
         "_id": "57addab291685f2a6762eb30",
         "index": 13,
         "guid": "f2b64858-485e-4d7b-9094-4063d1996d5a",
         "isActive": false,
         "balance": "$3,110.24",
         "picture": "http://placehold.it/32x32",
         "age": 33,
         "eyeColor": "brown",
         "name": "Fowler Perez",
         "gender": "male",
         "company": "PUSHCART",
         "email": "fowlerperez@pushcart.com",
         "phone": "+1 (870) 556-2790",
         "address": "142 Howard Alley, Faywood, North Dakota, 8000",
         "about": "Laborum tempor officia consequat culpa. Enim duis adipisicing deserunt laboris ut laboris irure consectetur nisi officia. Incididunt exercitation id quis exercitation quis nulla.\r\n"
     },
     {
         "_id": "57addab26190a5f95e6dc9ca",
         "index": 14,
         "guid": "bef7dd18-ff10-4d22-a91f-db6eeccfed91",
         "isActive": true,
         "balance": "$2,035.28",
         "picture": "http://placehold.it/32x32",
         "age": 32,
         "eyeColor": "green",
         "name": "Alfreda Monroe",
         "gender": "female",
         "company": "INQUALA",
         "email": "alfredamonroe@inquala.com",
         "phone": "+1 (919) 570-2803",
         "address": "949 Celeste Court, Ventress, Virginia, 4771",
         "about": "Nostrud laborum et quis laborum pariatur adipisicing esse exercitation ex. Occaecat magna fugiat consectetur Lorem nostrud deserunt Lorem voluptate est ipsum magna. Amet aliquip dolore velit ad Lorem.\r\n"
     },
     {
         "_id": "57addab2d71f6fc5af04aa54",
         "index": 15,
         "guid": "5a615d93-b024-44f8-a6ef-39e33fbb0855",
         "isActive": false,
         "balance": "$3,981.04",
         "picture": "http://placehold.it/32x32",
         "age": 36,
         "eyeColor": "green",
         "name": "Wilcox Munoz",
         "gender": "male",
         "company": "PATHWAYS",
         "email": "wilcoxmunoz@pathways.com",
         "phone": "+1 (970) 533-2723",
         "address": "648 Kaufman Place, Loretto, Nebraska, 8847",
         "about": "Culpa cillum ex anim voluptate. Consectetur proident quis labore eiusmod non labore cillum mollit sit proident est ad culpa officia. Mollit sit laborum dolor anim elit cillum laborum fugiat commodo amet ipsum commodo sunt. Culpa minim magna enim enim nulla. Qui minim cupidatat aliqua amet excepteur minim consectetur sint consequat est fugiat dolore aliquip. Consequat elit consectetur aute id minim aute labore consectetur esse ullamco sit cupidatat nisi.\r\n"
     }
 ];

export default data;